version: "3.7"
services: 
 nodejs:
   build: ./nodejs
   container_name: nodejs
   ports:
     - "3000:3000" 
 postgres:
    image: postgres
    container_name: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

 psql_data:
   driver: local
   name: psql_data
